### ____ _
# ____ _____ __ / ___ \ _ _ __ _ _ ____ | | |
# / __ // _ \ \ / / / _ | | | | | | / _ '| '_ / _' |
# \ __ \ __ /> <\ \ _ | | | | _ | | | | (_) | || (_) |
# / ___ / \ ___ / _ / \ _ \\ ____ / \ ___ / \ __, _ | _ | \ __, _ |
#
# MAIN CONFIGURATION FILE
###
# AUTHOR: sex_KAMAZ
# CONTACT: vk.com/infernopage
# t.me/sex_kamaz
# HELP: t.me/joinchat/EbZB3BKGfsu0DdbDNmpPjg
###
# PERMISSIONS:
# sexguard.command.rg: access to the main command.
# default: for all players.
#
# sexguard.noflag: the ability to ignore flags.
# default: for operators.
#
# sexguard.all: full access.
# default: for operators.
###
# ADDITIONAL PLUGINS:
#PurePerms: control of size and quantity
# regions for groups.
# UniGroup: alternative group manager.
# EconomyAPI: buying and selling regions.
# UniMoney: alternative economy.
###
# ERRORS IN THE WORK OF PLUGIN?
# Make sure that accidentally
# did not delete one of the items
# settings.
# To return the config to its
# the normal state is simple
# delete it - it will be restored
# when the plug-in is turned on.
###
sign: 5856cd0ba5aac216328752e444c9565c


###
# COMMUNICATION WITH PurePerms:
# Allow the plug-in to work with the permissions manager
# to determine the size and number of regions for
# each (or separate) of its groups.
# Otherwise, it will be used
# item default in group.yml for all players.
# You can configure groups in group.yml.
###
# AUTHORIZED: true
#BALD: false
allow_pureperms: false
###
# COMMUNICATION WITH UniGroup:
# Allow the plug-in to work with an alternative
# group manager.
###
# AUTHORIZED: true
#BALD: false
allow_universalgroup: false


###
# COMMUNICATION WITH EconomyAPI:
# Allow the plug-in to work with the economy
# for sale of regions.
# Actual for roleplay and survival.
###
# AUTHORIZED: true
#BALD: false
allow_economyapi: false
###
# COMMUNICATION WITH UNIMoney:
# Allow the plug-in to work with an alternative
# economy.
###
# AUTHORIZED: true
#BALD: false
allow_universalmoney: false
###
# SALE OF THE REGION THROUGH THE PLATE:
# (requires communication with the economy)
# Allow owners to sell
# their regions through the tablet.
# Actual for creating apartments.
###
# SHAPE FORM:
# 1 line: sell region
# 2 line: <price>
# 3 line:
# 4 line:
###
# ACTIVATE: true
# SWITCH: false
allow_sell: false
###
# PAYMENT FOR THE CREATION OF THE REGION:
# (requires communication with the economy)
# Set a mandatory fee for players
# without full access to create a new region
# using the command.
###
# AUTHORIZED: true
#BALD: false
pay_for_region: false
###
# PRICE FOR THE CREATION OF A NEW REGION:
# (you need to allow the payment option for the region)
# Set the price for creating a new region
# players without full access.
price: 200


###
# SAFE MODE:
# Prevents players without full access
# put and break blocks until they are
# are outside the region with the allowed
# on that flag, or outside your region.
# Actual for roleplay and minigames.
###
# ACTIVATE: true
# SWITCH: false
safe_mode: false


###
# REGION REGIME IN ALL HEIGHT:
# In this mode, each new region
# will be created without height
# (like chunk).
# Do not know, fuck someone need this feature,
# but create regions with it really
# conveniently.
# Please note that in the size settings
# of regions instead of their volume in blocks will be
# calculate the area (without height).
###
# ACTIVATE: true
# SWITCH: false
full_height: false


###
# ALERT TYPE:
# A way to notify players when
# prohibition of actions within the regions.
###
#POPUP: 0
# MESSAGE: 1
# TIP: 2
warn_type: 2


###
# FLAGS:
# Default flag values
# when creating a new region.
###
# INTERACT: opening chests, pressing buttons, etc.
# TELEPORT: teleportation from the region.
# EXPLODE: any explosions inside the region.
# CHANGE: changing the region by creatures.
# BUCKET: the use of buckets.
# DAMAGE: Taking damage from the outside world.
# CHEST: access to the chests.
# PLACE: the ability to put blocks.
#BREAK: the ability to break blocks.
# SLEEP: the opportunity to go to bed.
# DECAY: Allow the foliage to disappear from the trees.
# DROP: the ability to throw things away.
# CHAT: sending messages to the chat.
# PVP: the ability to deal damage to players.
# MOB: the ability to damage creatures.
###
# To prohibit players from using
# any flag, just delete it or
# comment out it.
# But only after you create
# the regions you need (spawn, arena, etc.)
# (put # before the item)
###
# ENABLE: true
# SWITCH: false
allowed_flag:
  Interact: true
  teleport: true
  explode: false
  change: false
  bucket: false
  damage: true
  chest: false
  place: false
  break: false
  sleep: false
  decay: true
  drop: true
  chat: true
  pvp: false
  mob: true
